### ISSUE TITLE
Random send to `beneficiary` when we talk about contributor?

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#19] opened 2018-05-04 00:07 UTC
https://github.com/kleros/openiico-contract/blob/master/contracts/IICO.sol#L218

`beneficiary.send(localSumAcceptedContrib); // Use send in order to not block if the contributor's fallback reverts.`

I think it should be part of `redeem` function anyway.

https://github.com/kleros/openiico-contract/blob/master/contracts/IICO.sol#L232-L243

```
        if (bid.maxVal > cutOffBid.maxVal || (bid.maxVal == cutOffBid.maxVal && _bidID >= cutOffBidID)) // Give tokens if the bid is accepted.
            token.transfer(bid.contributor, (tokensForSale * (bid.contrib + (bid.contrib * bid.bonus) / BONUS_DIVISOR)) / sumAcceptedVirtualContrib);
        else                                                                                            // Reimburse ETH otherwise.
            bid.contributor.transfer(bid.contrib);
```

In that specific instance we can send both tokens and overflow ETH.

PS. I really like your style of coding, long lines means more code visible on the screen.

**Comment by stefek99** [comment] 2018-05-04 14:41
Copy-paste comment error, now I understand better. Thanks!

**Comment by clesaege** [comment] 2018-05-04 15:47
Yeah, fixed in https://github.com/kleros/openiico-contract/commit/f1a81cb0f72ed7411b6ad6487d4cc1255ad0641e

The compiler gives warning when using send. So we put comment to let people be aware that this is the expected behaviour.
In the past, the warning made sense due to a callstack attack (which could force the send to fail), but this one is not possible anymore due to how gas works now.

**Closed by clesaege** 2018-05-04 15:47 UTC
